# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            "Learning OSS"
tagline:          'Personal Blog'
description:      '"Live as if you were to die tomorrow. Learn as if you were to live forever." <span style="font-size:18px">- Mahatma Gandhi <span/>'
disclosure:       "Opinions are my own and not the views of any company. Blog content/code doesn't have any warranty, please use as your own risk."
url:              https://learningoss.com
baseurl:          /

author:
  name:           'Edison Garcia'
  url:            https://github.com/egachi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/egachi

# Google Analytics
google_analytics: G-WZL57VMGHB

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - vendor/

sass:
  sass_dir: _sass
  style: :compressed